### ISSUE TITLE
manifest file

### ISSUE THREAD

**Issue by DaShaKha11** [AlessandroAnnini/udemy-openai#1]
First off, this is an amazing idea. I'm just having some trouble when I try to unpack the extension into chrome (also, your link to the chrome extension isn't working). I've attached my error message. 
<img width="501" alt="image" src="https://github.com/AlessandroAnnini/udemy-openai/assets/133789342/ca4d1068-c2d8-45d3-a65f-78e8065abba8">

**Comment by AlessandroAnnini** [comment]
Hi @DaShaKha11, thank you for your kind words.
The extension was taken down because it was not working with long texts (too many tokens).
Now I have fixed the bug and summaries from video of any length are possible and [the extension is available again at this link](https://chrome.google.com/webstore/detail/udemy-summary-with-openai/pknbmeegiiandmpcbldolgljempehfoe).

I am actively developing it to generate similar summaries from other video websites too.

**Comment by DaShaKha11** [comment]
Hi Alessandro, thanks for re-opening the extension. However, when I try to use it, it just keeps loading. Even after I inputted my API key. I tried multiple times as well.
<img width="404" alt="Screen Shot 2023-05-27 at 7 01 58 PM" src="https://github.com/AlessandroAnnini/udemy-openai/assets/133789342/01957807-b45e-4eea-aacf-448aeb5ab77b">
